<div class="container-fluid h-100">
	<div class="row">
    
    <div class="col-md-6 banner bg-warning">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
				<div class="communicationItem">
					<i class="fas fa-search fa-2x mr-3"></i>
					Procure o que lhe interessa.
				</div>
				<div class="communicationItem">
					<i class="fas fa-warehouse fa-2x mr-3"></i>
					Saiba os melhores lava-rápido.
				</div>
				<div class="communicationItem">
					<i class="far fa-comment fa-2x mr-3"></i>
					Participe.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
		<form method="post" action="/autenticar">
			<div class="row">
				<div class="col">
					<input type="text" name="email" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="password" name="senha" class="form-control" placeholder="Senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-warning mb-2">Entrar</button>
				</div>
			</div>
			
			<?php if($this->view->login == 'erro') { ?>
				<div class="row">
					<div class="col">
						<span class="text text-danger">*E-mail e ou senha inválido(s)</span>
					</div>
				</div>
			<?php } ?>
			
		</form>

		<div class="row pt-2 pl-2 pr-2">
			<div class="col pl-2 pr-2">
				
				<h1 class="title">Busque pelos melhores lava-rápido</h1>

				<h2 class="mt-5 subtitle">Participe hoje do MeLave.</h2>
				<a href="/inscreverse" class="btn btn-warning btn-block mb-2">Inscrever-se</a>
			</div>	
		</div>


    </div>

  </div>
</div>