<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">Nome da empresa</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Serviços</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Clientes</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Total de Agendamentos</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/comentario">
						<textarea class="form-control" name="comentario" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Adicionar Serviço</button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach($this->view->comentarios as $id_comentario => $comentario) { ?>	
				<div class="row tweet">
					<div class="col">
						<p><strong><?= $comentario['nome'] ?></strong> <small><span class="text text-muted">- <?= $comentario['data'] ?></span></small></p>
						<p><?= $comentario['comentario'] ?></p>

						<br />
						<form>
							<div class="col d-flex justify-content-end">
								<button type="submit" class="btn btn-danger"><small>Remover</small></button>
							</div>
						</form>
					</div>
				</div>
	<?php } ?>	

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Procure por empresas</span><br />
				<hr />
				<a href="/quem_favoritar" class="quemSeguirTxt">Procurar por empresas conceituadas no mercado</a>
			</div>
		</div>

	</div>
</div>